In [21]:
import pandas as pd

df = pd.read_csv("/kaggle/input/private-dataset/games.csv")

In [22]:
df.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,DiscountDLC count,About the game,Supported languages,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,[],...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",['English'],...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...","['English', 'French', 'German', 'Russian']",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",['Korean'],...,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,['English'],...,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

There seems to be an error in the column names with the name column having dates and the dates column containing the estimates owners. The problem seems to be coming from the `discountDLCcount` column which should actually be 2 columns. To fix this we will split this column into 2 columns `discount` and `DLCcount`. To do this we will rename the columns.

In [23]:

df = df.reset_index()

# we rename the columns by taking a copy of the orginal and splitting Discount and DLC count
df.columns = ['AppId','Name', 'Release date', 'Estimated owners', 'Peak CCU',
       'Required age', 'Price', 'Discount', 'DLC count', 'About the game',
       'Supported languages', 'Full audio languages', 'Reviews',
       'Header image', 'Website', 'Support url', 'Support email', 'Windows',
       'Mac', 'Linux', 'Metacritic score', 'Metacritic url', 'User score',
       'Positive', 'Negative', 'Score rank', 'Achievements', 'Recommendations',
       'Notes', 'Average playtime forever', 'Average playtime two weeks',
       'Median playtime forever', 'Median playtime two weeks', 'Developers',
       'Publishers', 'Categories', 'Genres', 'Tags', 'Screenshots', 'Movies']

remove `AppId` as the index column

In [24]:
# for that sake of consistency and readability of code we will make all column names snake case
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(" ", "_")

In [25]:
# a look at the fixed data frame
df.head()

,appid,name,release_date,estimated_owners,peak_ccu,required_age,price,discount,dlc_count,about_the_game,...,average_playtime_two_weeks,median_playtime_forever,median_playtime_two_weeks,developers,publishers,categories,genres,tags,screenshots,movies
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",...,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
4,3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,...,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125855 entries, 0 to 125854
Data columns (total 40 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   appid                       125855 non-null  int64
 1   name                        125854 non-null  object
 2   release_date                125855 non-null  object
 3   estimated_owners            125855 non-null  object
 4   peak_ccu                    125855 non-null  int64
 5   required_age                125855 non-null  int64
 6   price                       125855 non-null  float64
 7   discount                    125855 non-null  int64
 8   dlc_count                   125855 non-null  int64
 9   about_the_game              117393 non-null  object
 10  supported_languages         125855 non-null  object
 11  full_audio_languages        125855 non-null  object
 12  reviews                     12181 non-null   object
 13  header_image                125774 non-null  object
 14  website                     50520 non-null   object
 15  support_url                 55295 non-null   object
 16  support_email               103225 non-null  object
 17  windows                     125855 non-null  bool
 18  mac                         125855 non-null  bool
 19  linux                       125855 non-null  bool
 20  metacritic_score            125855 non-null  int64
 21  metacritic_url              4258 non-null    object
 22  user_score                  125855 non-null  int64
 23  positive                    125855 non-null  int64
 24  negative                    125855 non-null  int64
 25  score_rank                  40 non-null      float64
 26  achievements                125855 non-null  int64
 27  recommendations             125855 non-null  int64
 28  notes                       23310 non-null   object
 29  average_playtime_forever    125855 non-null  int64
 30  average_playtime_two_weeks  125855 non-null  int64
 31  median_playtime_forever     125855 non-null  int64
 32  median_playtime_two_weeks   125855 non-null  int64
 33  developers                  117406 non-null  object
 34  publishers                  116933 non-null  object
 35  categories                  116889 non-null  object
 36  genres                      117432 non-null  object
 37  tags                        83353 non-null   object
 38  screenshots                 119828 non-null  object
 39  movies                      0 non-null       float64
dtypes: bool(3), float64(3), int64(15), object(19)
memory usage: 35.9+ MB

In [27]:
df.describe(include="all")

,appid,name,release_date,estimated_owners,peak_ccu,required_age,price,discount,dlc_count,about_the_game,...,average_playtime_two_weeks,median_playtime_forever,median_playtime_two_weeks,developers,publishers,categories,genres,tags,screenshots,movies
count,1.258550e+05,125854,125855,125855,1.258550e+05,125855.000000,125855.000000,125855.000000,125855.000000,117393,...,125855.000000,1.258550e+05,125855.000000,117406,116933,116889,117432,83353,119828,0.0
unique,NaN,124644,5141,14,NaN,NaN,NaN,NaN,NaN,116776,...,NaN,NaN,NaN,72859,64607,14058,2922,77184,119718,NaN
top,NaN,Shadow of the Tomb Raider: Definitive Edition,"Oct 23, 2025",0 - 20000,NaN,NaN,NaN,NaN,NaN,Help the beautiful girls to immerse themselves...,...,NaN,NaN,NaN,EroticGamesClub,BFG Entertainment,"Single-player,Family Sharing","Casual,Indie","Adventure,Casual,Hidden Object",https://shared.akamai.steamstatic.com/store_it...,NaN
freq,NaN,20,190,75705,NaN,NaN,NaN,NaN,NaN,65,...,NaN,NaN,NaN,232,554,23878,6912,273,20,NaN
mean,2.032627e+06,NaN,NaN,NaN,5.318720e+01,0.165365,4.811174,17.896826,0.535434,NaN,...,13.507711,1.691803e+02,14.419125,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,1.117434e+06,NaN,NaN,NaN,3.681083e+03,1.642666,12.489329,28.628518,14.328417,NaN,...,266.925759,1.105725e+04,290.747134,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000e+01,NaN,NaN,NaN,0.000000e+00,0.000000,0.000000,0.000000,0.000000,NaN,...,0.000000,0.000000e+00,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1.083495e+06,NaN,NaN,NaN,0.000000e+00,0.000000,0.590000,0.000000,0.000000,NaN,...,0.000000,0.000000e+00,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1.949010e+06,NaN,NaN,NaN,0.000000e+00,0.000000,2.390000,0.000000,0.000000,NaN,...,0.000000,0.000000e+00,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2.938410e+06,NaN,NaN,NaN,0.000000e+00,0.000000,5.545000,37.000000,0.000000,NaN,...,0.000000,0.000000e+00,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,4.437540e+06,NaN,NaN,NaN,1.013936e+06,21.000000,999.980000,100.000000,3703.000000,NaN,...,20088.000000,3.429544e+06,20088.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
# take a look at null values in data
df.isnull().sum()

appid                              0
name                               1
release_date                       0
estimated_owners                   0
peak_ccu                           0
required_age                       0
price                              0
discount                           0
dlc_count                          0
about_the_game                  8462
supported_languages                0
full_audio_languages               0
reviews                       113674
header_image                      81
website                        75335
support_url                    70560
support_email                  22630
windows                            0
mac                                0
linux                              0
metacritic_score                   0
metacritic_url                121597
user_score                         0
positive                           0
negative                           0
score_rank                    125815
achievements                       0
recommendations                    0
notes                         102545
average_playtime_forever           0
average_playtime_two_weeks         0
median_playtime_forever            0
median_playtime_two_weeks          0
developers                      8449
publishers                      8922
categories                      8966
genres                          8423
tags                           42502
screenshots                     6027
movies                        125855
dtype: int64

There seems to be a few columns that contain null values. We will go through then let's start with name.

In [29]:
print(df[df['name'].isna()])

        appid name release_date estimated_owners  peak_ccu  required_age  \
44432  396420  NaN  Nov 1, 2016            0 - 0         0             0

       price  discount  dlc_count  \
44432    0.0         0          0

                                          about_the_game  ...  \
44432  Spookeningは3Dの恐怖ゲームで、あなたは毎夜に死んでゴーストとして復活します。 村...  ...

      average_playtime_two_weeks median_playtime_forever  \
44432                          0                       0

      median_playtime_two_weeks developers publishers categories genres  tags  \
44432                         0        NaN        NaN        NaN    NaN   NaN

       screenshots  movies
44432          NaN     NaN

[1 rows x 40 columns]

The game seems to have a name but doesn't as in its description it calls itself "spookening", but it doesn't seem to be in the dataset. We will remove this entry for the sake of consistency.

In [30]:
#removing entry without name
df = df[df['name'].isna() != True]

looking at the number of entries that have no movies we can see that is the same as the total number of entries that means no entry has a movie entry, and thus we can just delete the column.

In [31]:
#dropping movie column
df = df.drop(columns=['movies'])

The remaining columns that contain a null value seem fine. They all are able to occur naturally in the data.

For this analysis of what makes a game popular we will be mostly looking at the `Estimated Owners` column

In [32]:
#take a look at the different categories in `estimated owners` column
df['estimated_owners'].value_counts()

estimated_owners
0 - 20000                75705
0 - 0                    24578
20000 - 50000            11397
50000 - 100000            5355
100000 - 200000           3454
200000 - 500000           2856
500000 - 1000000          1155
1000000 - 2000000          729
2000000 - 5000000          405
5000000 - 10000000         125
10000000 - 20000000         51
20000000 - 50000000         31
50000000 - 100000000         9
100000000 - 200000000        4
Name: count, dtype: int64

There seems to be a lot of games with 0 - 0 estimated owners. I wonder what is going on there. Let's look at a few of them

In [33]:
df[df['estimated_owners'] == '0 - 0'].head(10)

,appid,name,release_date,estimated_owners,peak_ccu,required_age,price,discount,dlc_count,about_the_game,...,average_playtime_forever,average_playtime_two_weeks,median_playtime_forever,median_playtime_two_weeks,developers,publishers,categories,genres,tags,screenshots
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...
10,1946890,Codename: Warlock Playtest,"Mar 25, 2022",0 - 0,0,0,0.00,0,0,NaN,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...
18,2260230,Midnight Dash,"Jan 9, 2023",0 - 0,0,0,0.00,0,0,Story! The game tells you a story about Sean w...,...,0,0,0,0,Saku Hållfast,Saku Hållfast,"Single-player,Multi-player,PvP,Shared/Split Sc...","Action,Adventure,Indie,Free To Play,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...
20,2713630,Black Market,"Jan 24, 2025",0 - 0,0,0,0.00,0,0,Black Market is an item shop simulator where y...,...,0,0,0,0,Wani Games LLC,Wani Games LLC,Single-player,"Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...
24,2349750,CyberVault Playtest,"Mar 8, 2023",0 - 0,0,0,0.00,0,0,NaN,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
25,2628280,A Night In Omar's Burger Playtest,"Oct 4, 2023",0 - 0,0,0,0.00,0,0,NaN,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...
39,2731180,Blaster Multiplayer,"Jan 2, 2024",0 - 0,0,0,0.00,0,0,About This Game Overview: Immerse yourself in ...,...,0,0,0,0,Guillaume Norgol,Guillaume Norgol,"Multi-player,PvP,Online PvP,Full controller su...",Action,NaN,https://shared.akamai.steamstatic.com/store_it...
44,3854040,BRUTALISMUS: Dystopia,"Jul 31, 2025",0 - 0,0,0,1.39,0,1,Can you escape the structures of your own mind...,...,0,0,0,0,ETERNIDAD,ETERNIDAD,"Single-player,Steam Achievements,Custom Volume...","Adventure,Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...
45,2310500,Ortheo's Interdimensional Jam Session,"Aug 10, 2023",0 - 0,0,0,0.00,0,0,Get ready to rock and groove with Ortheo's Int...,...,0,0,0,0,Larsonsoft,Larsonsoft,"Single-player,Steam Achievements,Includes leve...","Action,Indie,Free To Play",NaN,https://shared.akamai.steamstatic.com/store_it...
46,2641000,Spider-Guy: Trapped in the Cheese Place,"Feb 21, 2024",0 - 0,0,0,0.00,0,0,Spider-guy has been imprisoned by the dastardl...,...,0,0,0,0,KrackedGames,KrackedGames,"Single-player,Full controller support","Action,Adventure,Indie",NaN,https://shared.akamai.steamstatic.com/store_it...

Most of these games seem to be playtests, while others seem to be just very unpopular games or games that have been taken off of steam. I would be beneficial to keep the unpopular games that are not playtests and are still up on steam that would be practically impossible. The only other option is getting rid of all of them.

In [34]:
#removing 0-0 counts
df = df[df['estimated_owners'] != '0 - 0']
#checking categories agian
df['estimated_owners'].value_counts()

estimated_owners
0 - 20000                75705
20000 - 50000            11397
50000 - 100000            5355
100000 - 200000           3454
200000 - 500000           2856
500000 - 1000000          1155
1000000 - 2000000          729
2000000 - 5000000          405
5000000 - 10000000         125
10000000 - 20000000         51
20000000 - 50000000         31
50000000 - 100000000         9
100000000 - 200000000        4
Name: count, dtype: int64

To make the numbers easier to read we replace 1000 with K and 1000000 with M

In [35]:
#define a dictionary for the reduction
number_to_reduced_number = {
    '0 - 20000': '0 - 20K',
    '20000 - 50000': '20K - 50K',
    '50000 - 100000': '50K - 100K',
    '100000 - 200000': '100K - 200K',
    '200000 - 500000': '200K - 500K',
    '500000 - 1000000': '500K - 1M',
    '1000000 - 2000000': '1M - 2M',
    '2000000 - 5000000': '2M - 5M',
    '5000000 - 10000000': '5M - 10M',
    '10000000 - 20000000': '10M - 20M',
    '20000000 - 50000000': '20M - 50M',
    '50000000 - 100000000': '50M - 100M',
    '100000000 - 200000000': '100M - 200M'}

df['estimated_owners'] = df['estimated_owners'].map(number_to_reduced_number)
df['estimated_owners'].value_counts()

estimated_owners
0 - 20K        75705
20K - 50K      11397
50K - 100K      5355
100K - 200K     3454
200K - 500K     2856
500K - 1M       1155
1M - 2M          729
2M - 5M          405
5M - 10M         125
10M - 20M         51
20M - 50M         31
50M - 100M         9
100M - 200M        4
Name: count, dtype: int64

# Prep for Sql

Let's start by droppig some not very useful fields for analysis. For example: header_image, metacritic_url, etc.

In [36]:
df = df.drop(columns=['about_the_game', 'screenshots', 'movies', 'header_image', 'metacritic_url', 'support_url', 'support_email', 'website', 'screenshots', 'notes'], errors='ignore')
df.shape
df.columns

Index(['appid', 'name', 'release_date', 'estimated_owners', 'peak_ccu',
       'required_age', 'price', 'discount', 'dlc_count', 'supported_languages',
       'full_audio_languages', 'reviews', 'windows', 'mac', 'linux',
       'metacritic_score', 'user_score', 'positive', 'negative', 'score_rank',
       'achievements', 'recommendations', 'average_playtime_forever',
       'average_playtime_two_weeks', 'median_playtime_forever',
       'median_playtime_two_weeks', 'developers', 'publishers', 'categories',
       'genres', 'tags'],
      dtype='object')

Let's make a genres and categories table more easily query based on genre and category.

In [37]:
#creating genre table, and genre_to_game table
genres_df = df[['appid', 'genres']].dropna()

genres_df = genres_df.assign(
    genre=genres_df['genres'].str.split(',')
).explode('genre')

genres_df['genre'] = genres_df['genre'].str.strip()

unique_genres = genres_df['genre'].drop_duplicates().reset_index(drop=True)

genres_table = pd.DataFrame({
    'genre_id': range(1, len(unique_genres) + 1),
    'genre_name': unique_genres
})

genre_map = dict(zip(genres_table['genre_name'], genres_table['genre_id']))

genres_df['genre_id'] = genres_df['genre'].map(genre_map)

game_genres = genres_df[['appid', 'genre_id']]

df = df.drop(columns=['genres'])

#creating tag table, and tag_to_game table
tags_df = df[['appid', 'tags']].dropna()

tags_df = tags_df.assign(
    tags=tags_df['tags'].str.split(',')
).explode('tags')

tags_df['tags'] = tags_df['tags'].str.strip()

unique_tags = tags_df['tags'].drop_duplicates().reset_index(drop=True)

tag_table = pd.DataFrame({
    'tag_id': range(1, len(unique_tags) + 1),
    'tag_name': unique_tags
})

tag_map = dict(zip(tag_table['tag_name'], tag_table['tag_id']))

tags_df['tag_id'] = tags_df['tags'].map(tag_map)

game_tags = tags_df[['appid', 'tag_id']]

df = df.drop(columns=['tags'])

make a set of tables for `supported_languages`

In [38]:
# languages
languages_df = df[['appid', 'supported_languages']].dropna()

languages_df = languages_df.assign(
    supported_languages=languages_df['supported_languages'].str.strip("[]").str.split("', '")
).explode('supported_languages')

languages_df['supported_languages'] = (
    languages_df['supported_languages']
    .str.strip("'")
    .str.strip()
)

languages_df['supported_languages'] = languages_df['supported_languages'].str.strip()

unique_languages = languages_df['supported_languages'].drop_duplicates().reset_index(drop=True)

languages_table = pd.DataFrame({
    'languages_id': range(1, len(unique_languages) + 1),
    'languages_name': unique_languages
})

languages_map = dict(zip(languages_table['languages_name'], languages_table['languages_id']))

languages_df['languages_id'] = languages_df['supported_languages'].map(languages_map)

game_languages = languages_df[['appid', 'languages_id']]

It seems supported languages has some messy data. We will look though all languages and keep make a .csv with plausible languages. We will redo the conversion with the new list of languages.

In [39]:
language_names = [
    'English', 'French', 'German', 'Russian', 'Korean', 'Italian',
    'Spanish - Spain', 'Polish', 'Portuguese - Portugal', 'Turkish',
    'Bulgarian', 'Simplified Chinese', 'Traditional Chinese', 'Danish',
    'Spanish - Latin America', 'Finnish', 'Greek', 'Dutch', 'Hungarian',
    'Japanese', 'Norwegian', 'Portuguese - Brazil', 'Romanian', 'Swedish',
    'Thai', 'Czech', 'Ukrainian', 'Vietnamese', 'Arabic', 'Belarusian',
    'Malay', 'Indonesian', 'Afrikaans', 'Albanian', 'Amharic', 'Armenian',
    'Assamese', 'Azerbaijani', 'Bangla', 'Basque', 'Bosnian', 'Catalan',
    'Cherokee', 'Croatian', 'Dari', 'Estonian', 'Filipino', 'Galician',
    'Georgian', 'Gujarati', 'Hausa', 'Hebrew', 'Hindi', 'Icelandic',
    'Igbo', 'Irish', 'Kannada', 'Kazakh', 'Khmer', 'Kinyarwanda',
    'Konkani', 'Kyrgyz', 'Latvian', 'Lithuanian', 'Luxembourgish',
    'Macedonian', 'Malayalam', 'Maltese', 'Maori', 'Marathi', 'Mongolian',
    'Nepali', 'Odia', 'Persian', 'Punjabi (Gurmukhi)',
    'Punjabi (Shahmukhi)', 'Quechua', 'Scots', 'Serbian', 'Sindhi',
    'Sinhala', 'Slovak', 'Slovenian', 'Sorani', 'Sotho', 'Swahili',
    'Tajik', 'Tamil', 'Tatar', 'Telugu', 'Tigrinya', 'Tswana', 'Turkmen',
    'Urdu', 'Uyghur', 'Uzbek', 'Valencian', 'Welsh', 'Wolof', 'Xhosa',
    'Yoruba', 'Zulu'
]

languages_df = languages_df.assign(
    languages=languages_df['supported_languages'].apply(
        lambda x: [language for language in language_names if language in str(x)]
    )
).explode('languages')

unique_languages = languages_df['languages'].drop_duplicates().reset_index(drop=True)

languages_table = pd.DataFrame({
    'languages_id': range(1, len(unique_languages) + 1),
    'languages_name': unique_languages
})

languages_map = dict(zip(languages_table['languages_name'], languages_table['languages_id']))

languages_df['languages_id'] = languages_df['supported_languages'].map(languages_map)

game_languages = languages_df[['appid', 'languages_id']].drop_duplicates()

game_languages = game_languages.dropna()

game_languages['languages_id'] = (
    game_languages['languages_id'].astype(int)
)

df = df.drop(columns=['supported_languages'])

exporting from kaggle to .csv to import on local postgres

In [40]:
bad_rows = df[df.astype(str).apply(lambda x: x.str.contains("\x9d", regex=False)).any(axis=1)]

print(bad_rows)

Empty DataFrame
Columns: [appid, name, release_date, estimated_owners, peak_ccu, required_age, price, discount, dlc_count, full_audio_languages, reviews, windows, mac, linux, metacritic_score, user_score, positive, negative, score_rank, achievements, recommendations, average_playtime_forever, average_playtime_two_weeks, median_playtime_forever, median_playtime_two_weeks, developers, publishers, categories]
Index: []

[0 rows x 28 columns]

In [41]:
df.to_csv("/kaggle/working/games.csv", index=False, encoding="utf-8")
genres_table.to_csv("/kaggle/working/genres.csv", index=False)
game_genres.to_csv("/kaggle/working/game_genres.csv", index=False)

tag_table.to_csv("/kaggle/working/tags.csv", index=False)
game_tags.to_csv("/kaggle/working/game_tags.csv", index=False)

languages_table.to_csv("/kaggle/working/languages.csv", index=False)
game_languages.to_csv("/kaggle/working/game_languages.csv", index=False)

import os
print(os.listdir("/kaggle/working"))

['game_languages.csv', 'genres.csv', 'game_tags.csv', 'languages.csv', 'games.csv', 'game_genres.csv', '.virtual_documents', 'tags.csv']